machine:
  timezone: UTC
  java:
    version: oraclejdk8

dependencies:
  override:
    - mkdir -p ~/bin/
    - curl -o ~/bin/digdag -L "https://dl.digdag.io/digdag-latest"
    - chmod +x ~/bin/digdag

test:
  override:
    - digdag check

deployment:
  production:
    branch: master
    commands:
      - >
        digdag push $WF_PROJECT
        -e api-workflow.treasuredata.com
        -X client.http.headers.authorization="TD1 $TD_API_KEY"
        -r `date -u +"%Y-%m-%dT%H:%M:%SZ"`-`git rev-parse HEAD`
